Finish porting from slxsave, added localization support, added fstype option, added support for ext* fstype to complement xfs fstype, added some error checks.

diff --git a/src/persistence-wizard-cli b/src/persistence-wizard-cli
--- a/src/persistence-wizard-cli
+++ b/src/persistence-wizard-cli
@@ -1,25 +1,57 @@
 #!/bin/sh
+# Written by: Cyrille Pontvieux <jrd~at~enialis~dot~net>
+# Modified by: Pierrick Le Brun <akuna~at~free~dot~fr>
+
 version=1.0
-if [ -z "$1" ]; then
-  echo "$(basename $0) NAME SIZE_IN_MEGABYTES"
-  echo "  Will create a xfs file named NAME with the"
-  echo "  Corresponding size (in MB)."
-  echo "  Copy this file to the root directory of your USB key."
-  echo ""
-  echo "Copyright Cyrille Pontvieux - jrd@salixos.org"
-  echo "Released under GPL v3 or (at your option, any later version)"
-  echo "version = $version"
-  exit 1
+
+# Gettext internationalization
+export TEXTDOMAIN="persistence-wizard-cli"
+export TEXTDOMAINDIR="/usr/share/locale"
+. gettext.sh
+
+if [ `id -u` != "0" ]; then
+	echo "`eval_gettext 'ERROR: You need to be root to run'` $(basename $0)"
+	exit 1
 fi
-SIZE=$1
+
+if [ -z "$1" ]; then
+	echo "Usage: $(basename $0) `eval_gettext 'NAME SIZE_IN_MEGABYTES FS_TYPE'`"
+	echo ""
+	echo "`eval_gettext 'This will create a file named NAME with the corresponding '`"
+	echo "`eval_gettext 'size (in MB) and the corresponding file system type  '`" 
+	echo "" 
+	echo "`eval_gettext 'Copy this file to a directory named /salixlive/persistence '`"
+	echo "`eval_gettext 'either on your USB key or else on a hard disk drive if it '`"
+	echo "`eval_gettext 'will be used with a SaLT LiveCD.'`"
+	echo ""
+	echo "Copyright Cyrille Pontvieux - jrd@salixos.org"
+	echo "`eval_gettext 'Released under GPL v3 or (at your option, any later version)'`"
+	echo "version = $version"
+	exit 1
+fi
+
+NAME=$1
+SIZE=$2
+FS=$3
+
 FREE=$('df' -k .|tail -n1|awk '{print $4}')
 AFTER=$(( $FREE - 1024 * $SIZE ))
 if [ $AFTER -gt 0 ]; then
-  dd if=/dev/zero of=slxsave.xfs bs=1M count=$SIZE
-  mkfs.xfs -f slxsave.xfs
-  echo ""
-  echo "slxsave.xfs is ready."
+	dd if=/dev/zero of=$NAME.save bs=1M count=$SIZE
+	if [ $3 == "xfs" ]; then  
+		mkfs.$FS -f $NAME.save && CHECK="OK"
+	elif [[ $3 =~ "ext" ]]; then
+		mkfs.$FS -F $NAME.save && CHECK="OK"
+	fi
+	if [ $CHECK == "OK" ]; then
+		echo ""
+		echo "`eval_gettext 'The persistent file $NAME.save is ready.'`"
+	else
+		echo "`eval_gettext 'Sorry! '` $(basename $0) `eval_gettext ' was not able to create the persistent file $NAME.save'`"
+		exit 1
+	fi
 else
-  echo "Not enough free space left for creating slxsave.xfs in the current directory."
+  echo "`eval_gettext 'Sorry! There is not enough free space left on your device'`"
+  echo "`eval_gettext 'for creating the persistent file $NAME.save in the current directory.'`"
   exit 1
 fi
